# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 23:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0003_auto_20170620_0035'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Profile',
        ),
    ]
