# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0006_auto_20170620_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
